status = error

name = SparkLogConfig

rootLogger.level = info
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = Console

appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

logger.spark.name = org.apache.spark
logger.spark.level = warn

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn

logger.hive.name = org.apache.hadoop.hive
logger.hive.level = warn

logger.parquet.name = org.apache.parquet
logger.parquet.level = warn

logger.orc.name = org.apache.orc
logger.orc.level = warn

logger.aws.name = com.amazonaws
logger.aws.level = warn

logger.jetty.name = org.sparkproject.jetty
logger.jetty.level = warn